/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2-0-g3735e28-dirty

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: IO_Board_sim.xdd
        File Version: 1

        Created:      20.04.2026 15:00:00
        Created By:   Lukas Wendle
        Modified:     21.04.2026 08:16:18
        Modified By:  Lukas Wendle

    Device Info:
        Vendor Name:  MEIKO
        Vendor ID:    0x00000000
        Product Name: CANopen
        Product ID:   0x00000000

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_RPDO 1
#define OD_CNT_TPDO 2


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1016 1
#define OD_CNT_ARR_2000 12
#define OD_CNT_ARR_6000 2
#define OD_CNT_ARR_6001 2
#define OD_CNT_ARR_6002 8


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint32_t x1002_manufacturerStatusRegister;
    char x1008_manufacturerDeviceName[10];
    uint32_t x1014_emergencyCOB_ID;
    uint16_t x1015_inhibitTimeEmergency;
    uint8_t x1016_consumerHeartbeatTime_sub0;
    uint32_t x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t numberOfEntries;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t numberOfEntries;
        uint32_t COB_ID_ClientToServerReceiveSDO;
        uint32_t COB_ID_ServerToClientTransmitSDO;
    } x1200_serverSDO_Parameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByRPDO;
        uint8_t transmissionType;
        uint16_t eventTimer;
    } x1400_RPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1600_RPDOMappingParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1800_TPDOCommunicationParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDUsedByTPDO;
        uint8_t transmissionType;
        uint16_t inhibitTime;
        uint16_t eventTimer;
        uint8_t SYNCStartValue;
    } x1801_TPDOCommunicationParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A00_TPDOMappingParameter;
    struct {
        uint8_t numberOfMappedApplicationObjectsInPDO;
        uint32_t applicationObject1;
        uint32_t applicationObject2;
        uint32_t applicationObject3;
        uint32_t applicationObject4;
        uint32_t applicationObject5;
        uint32_t applicationObject6;
        uint32_t applicationObject7;
        uint32_t applicationObject8;
    } x1A01_TPDOMappingParameter;
    uint8_t x2000_digitalInputHardwareCapabilities_sub0;
    uint32_t x2000_digitalInputHardwareCapabilities[OD_CNT_ARR_2000];
    uint8_t x6000_digitalInputs_sub0;
    uint8_t x6000_digitalInputs[OD_CNT_ARR_6000];
    uint8_t x6001_digitalOutputs_sub0;
    uint8_t x6001_digitalOutputs[OD_CNT_ARR_6001];
    uint8_t x6002_analogValues_sub0;
    int16_t x6002_analogValues[OD_CNT_ARR_6002];
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1002 &OD->list[2]
#define OD_ENTRY_H1003 &OD->list[3]
#define OD_ENTRY_H1008 &OD->list[4]
#define OD_ENTRY_H1009 &OD->list[5]
#define OD_ENTRY_H100A &OD->list[6]
#define OD_ENTRY_H1014 &OD->list[7]
#define OD_ENTRY_H1015 &OD->list[8]
#define OD_ENTRY_H1016 &OD->list[9]
#define OD_ENTRY_H1017 &OD->list[10]
#define OD_ENTRY_H1018 &OD->list[11]
#define OD_ENTRY_H1200 &OD->list[12]
#define OD_ENTRY_H1400 &OD->list[13]
#define OD_ENTRY_H1600 &OD->list[14]
#define OD_ENTRY_H1800 &OD->list[15]
#define OD_ENTRY_H1801 &OD->list[16]
#define OD_ENTRY_H1A00 &OD->list[17]
#define OD_ENTRY_H1A01 &OD->list[18]
#define OD_ENTRY_H2000 &OD->list[19]
#define OD_ENTRY_H6000 &OD->list[20]
#define OD_ENTRY_H6001 &OD->list[21]
#define OD_ENTRY_H6002 &OD->list[22]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1002_manufacturerStatusRegister &OD->list[2]
#define OD_ENTRY_H1003_pre_definedErrorField &OD->list[3]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[4]
#define OD_ENTRY_H1009_manufacturerHardwareVersion &OD->list[5]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[6]
#define OD_ENTRY_H1014_emergencyCOB_ID &OD->list[7]
#define OD_ENTRY_H1015_inhibitTimeEmergency &OD->list[8]
#define OD_ENTRY_H1016_consumerHeartbeatTime &OD->list[9]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[10]
#define OD_ENTRY_H1018_identity &OD->list[11]
#define OD_ENTRY_H1200_serverSDO_Parameter &OD->list[12]
#define OD_ENTRY_H1400_RPDOCommunicationParameter &OD->list[13]
#define OD_ENTRY_H1600_RPDOMappingParameter &OD->list[14]
#define OD_ENTRY_H1800_TPDOCommunicationParameter &OD->list[15]
#define OD_ENTRY_H1801_TPDOCommunicationParameter &OD->list[16]
#define OD_ENTRY_H1A00_TPDOMappingParameter &OD->list[17]
#define OD_ENTRY_H1A01_TPDOMappingParameter &OD->list[18]
#define OD_ENTRY_H2000_digitalInputHardwareCapabilities &OD->list[19]
#define OD_ENTRY_H6000_digitalInputs &OD->list[20]
#define OD_ENTRY_H6001_digitalOutputs &OD->list[21]
#define OD_ENTRY_H6002_analogValues &OD->list[22]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
